# Generated by Django 3.1.6 on 2021-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=25),
        ),
    ]
