# Generated by Django 3.1.6 on 2021-02-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='products')),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('ratings_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
