# Generated by Django 3.1.6 on 2021-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
